### ISSUE TITLE
Strong token typing

### ISSUE THREAD

**Issue by mck** [tokens-studio/graph-engine#405]
```[tasklist]
### Tasks
- [ ] https://github.com/tokens-studio/graph-engine/issues/404
- [ ] https://github.com/tokens-studio/graph-engine/issues/406
- [ ] https://github.com/tokens-studio/graph-engine/issues/407
- [ ] https://github.com/tokens-studio/graph-engine/issues/409
- [ ] https://github.com/tokens-studio/graph-engine/issues/408
- [ ] https://github.com/tokens-studio/graph-engine/issues/411
```
